version: '3.8'

services:
  # PocketBase Database
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    restart: unless-stopped
    command:
      - --encryptionEnv=PB_ENCRYPTION_KEY
    environment:
      PB_ENCRYPTION_KEY: "your-32-char-encryption-key-here"
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb_data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8090/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # URL Shortening Service
  url-shortener:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      POCKETBASE_URL: http://pocketbase:8090
      PORT: 8080
      ENVIRONMENT: production
      SHORT_CODE_LENGTH: 6
      MAX_RETRIES: 5
    depends_on:
      pocketbase:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis (for future caching implementation)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pocketbase_data:
  redis_data:
